/**
 * ==========================================================================
 * Minidows OS - 100+ İşletim Sistemi Veritabanı
 * ==========================================================================
 */

window.MinidowsCatalog = [
    // --------------------------------------------------------------------------
    // 1. MINIDOWS AİLESİ (28 SİSTEM)
    // --------------------------------------------------------------------------
    {
        id: "minidows_1",
        name: "Minidows 1.0",
        category: "minidows",
        icon: "🪟",
        tagline: "1985 yılından ilk 16-bit pencere devrimi",
        themeClass: "wp-retro95",
        prompt: "C:\\MINIDOWS1>",
        startBtnIcon: "🪟",
        startBtnText: "Minidows 1",
        year: "1985",
        accent: "#008080"
    },
    {
        id: "minidows_2",
        name: "Minidows 2.0",
        category: "minidows",
        icon: "🪟",
        tagline: "Üst üste binen pencereler ve EGA renkleri",
        themeClass: "wp-retro95",
        prompt: "C:\\MINIDOWS2>",
        startBtnIcon: "🪟",
        startBtnText: "Minidows 2",
        year: "1987",
        accent: "#00a8a8"
    },
    {
        id: "minidows_31",
        name: "Minidows 3.1",
        category: "minidows",
        icon: "🪟",
        tagline: "Program Yöneticisi, Mayın Tarlası ve 16 renk",
        themeClass: "wp-retro95",
        prompt: "C:\\MINIDOWS31>",
        startBtnIcon: "🪟",
        startBtnText: "Minidows 3.1",
        year: "1992",
        accent: "#00557f"
    },
    {
        id: "minidows_311",
        name: "Minidows for Workgroups 3.11",
        category: "minidows",
        icon: "🪟",
        tagline: "İlk yerel ağ (LAN) ve TCP/IP desteği",
        themeClass: "wp-retro95",
        prompt: "C:\\MININET>",
        startBtnIcon: "🪟",
        startBtnText: "Minidows 3.11",
        year: "1993",
        accent: "#004080"
    },
    {
        id: "minidows_95",
        name: "Minidows 95",
        category: "minidows",
        icon: "🪟",
        tagline: "Efsane Başlat tuşu ve görev çubuğunun doğuşu",
        themeClass: "wp-retro95",
        prompt: "C:\\MINIDOWS95>",
        startBtnIcon: "🪟",
        startBtnText: "Başlat 95",
        year: "1995",
        accent: "#008080"
    },
    {
        id: "minidows_98",
        name: "Minidows 98",
        category: "minidows",
        icon: "🪟",
        tagline: "USB desteği, Internet Explorer ve masaüstü web",
        themeClass: "wp-retro95",
        prompt: "C:\\MINIDOWS98>",
        startBtnIcon: "🪟",
        startBtnText: "Başlat 98",
        year: "1998",
        accent: "#1e3a8a"
    },
    {
        id: "minidows_98_se",
        name: "Minidows 98 İkinci Sürüm (SE)",
        category: "minidows",
        icon: "🪟",
        tagline: "İnternet bağlantı paylaşımı ve kaya gibi kararlılık",
        themeClass: "wp-retro95",
        prompt: "C:\\MINIDOWS98SE>",
        startBtnIcon: "🪟",
        startBtnText: "Minidows 98SE",
        year: "1999",
        accent: "#2563eb"
    },
    {
        id: "minidows_me",
        name: "Minidows Millennium Edition (ME)",
        category: "minidows",
        icon: "🪟",
        tagline: "Milenyum coşkusu, Media Player ve Movie Maker",
        themeClass: "wp-bliss",
        prompt: "C:\\MINIDOWSME>",
        startBtnIcon: "🪟",
        startBtnText: "Minidows ME",
        year: "2000",
        accent: "#0284c7"
    },
    {
        id: "minidows_2000",
        name: "Minidows 2000 Professional",
        category: "minidows",
        icon: "🪟",
        tagline: "Kaya gibi sağlam profesyonel NT çekirdeği",
        themeClass: "wp-retro95",
        prompt: "C:\\WIN2KPRO>",
        startBtnIcon: "🪟",
        startBtnText: "Minidows 2000",
        year: "2000",
        accent: "#0369a1"
    },
    {
        id: "minidows_xp_home",
        name: "Minidows XP Home Edition",
        category: "minidows",
        icon: "🪟",
        tagline: "Yeşil başlat tuşu, mavi Luna teması ve Bliss tepeleri",
        themeClass: "wp-bliss",
        prompt: "C:\\Documents\\User>",
        startBtnIcon: "🪟",
        startBtnText: "Başlat XP",
        year: "2001",
        accent: "#22c55e"
    },
    {
        id: "minidows_xp_pro",
        name: "Minidows XP Professional",
        category: "minidows",
        icon: "🪟",
        tagline: "Uzak masaüstü, dosya şifreleme ve efsane kararlılık",
        themeClass: "wp-bliss",
        prompt: "C:\\MinidowsXP>",
        startBtnIcon: "🪟",
        startBtnText: "Minidows XP",
        year: "2001",
        accent: "#2563eb"
    },
    {
        id: "minidows_xp_black",
        name: "Minidows XP Black Edition",
        category: "minidows",
        icon: "🖤",
        tagline: "Siyah modifiye tema, tam sürücü paketi",
        themeClass: "wp-darkglass",
        prompt: "C:\\XP_BLACK>",
        startBtnIcon: "🖤",
        startBtnText: "XP Black",
        year: "2005",
        accent: "#64748b"
    },
    {
        id: "minidows_vista_home",
        name: "Minidows Vista Home Premium",
        category: "minidows",
        icon: "🪟",
        tagline: "Aero cam efektleri ve kenar çubuğu widget'ları",
        themeClass: "wp-darkglass",
        prompt: "C:\\Users\\Vista>",
        startBtnIcon: "🪟",
        startBtnText: "Vista",
        year: "2006",
        accent: "#0284c7"
    },
    {
        id: "minidows_vista_ultimate",
        name: "Minidows Vista Ultimate",
        category: "minidows",
        icon: "💎",
        tagline: "DreamScene hareketli duvar kağıtları ve tam Aero",
        themeClass: "wp-darkglass",
        prompt: "C:\\Users\\Ultimate>",
        startBtnIcon: "💎",
        startBtnText: "Vista Ult",
        year: "2007",
        accent: "#06b6d4"
    },
    {
        id: "minidows_7_home",
        name: "Minidows 7 Home",
        category: "minidows",
        icon: "🪟",
        tagline: "Aero Snap, sadeleştirilmiş süper görev çubuğu",
        themeClass: "wp-darkglass",
        prompt: "C:\\Users\\Min7>",
        startBtnIcon: "🪟",
        startBtnText: "Minidows 7",
        year: "2009",
        accent: "#38bdf8"
    },
    {
        id: "minidows_7_ultimate",
        name: "Minidows 7 Ultimate Kral",
        category: "minidows",
        icon: "👑",
        tagline: "Milyonların sevgilisi, gelmiş geçmiş en sevilen Minidows",
        themeClass: "wp-darkglass",
        prompt: "C:\\Users\\King7>",
        startBtnIcon: "👑",
        startBtnText: "Minidows 7",
        year: "2009",
        accent: "#3b82f6"
    },
    {
        id: "minidows_8",
        name: "Minidows 8 Metro",
        category: "minidows",
        icon: "🔲",
        tagline: "Kutucuklu tam ekran Metro başlat menüsü",
        themeClass: "wp-cyberpunk",
        prompt: "C:\\Users\\Metro8>",
        startBtnIcon: "🔲",
        startBtnText: "Minidows 8",
        year: "2012",
        accent: "#7c3aed"
    },
    {
        id: "minidows_81",
        name: "Minidows 8.1 Pro",
        category: "minidows",
        icon: "🪟",
        tagline: "Geri dönen başlat butonu ve doğrudan masaüstü açılışı",
        themeClass: "wp-cyberpunk",
        prompt: "C:\\Users\\Min81>",
        startBtnIcon: "🪟",
        startBtnText: "Minidows 8.1",
        year: "2013",
        accent: "#9333ea"
    },
    {
        id: "minidows_10_home",
        name: "Minidows 10 Home",
        category: "minidows",
        icon: "🪟",
        tagline: "Cortana, sanal masaüstleri ve modern bildirim merkezi",
        themeClass: "wp-darkglass",
        prompt: "C:\\Users\\Min10>",
        startBtnIcon: "🪟",
        startBtnText: "Minidows 10",
        year: "2015",
        accent: "#0284c7"
    },
    {
        id: "minidows_10_pro",
        name: "Minidows 10 Pro",
        category: "minidows",
        icon: "🪟",
        tagline: "BitLocker, Hyper-V ve tam iş istasyonu desteği",
        themeClass: "wp-darkglass",
        prompt: "C:\\Users\\Pro10>",
        startBtnIcon: "🪟",
        startBtnText: "Minidows 10 Pro",
        year: "2018",
        accent: "#2563eb"
    },
    {
        id: "minidows_11",
        name: "Minidows 11 Sun Valley",
        category: "minidows",
        icon: "🪟",
        tagline: "Ortalanmış simgeler, yuvarlatılmış köşeler ve akıcı Mica",
        themeClass: "wp-darkglass",
        prompt: "C:\\Users\\Minidows11>",
        startBtnIcon: "🪟",
        startBtnText: "Minidows 11",
        year: "2021",
        accent: "#38bdf8"
    },
    {
        id: "minidows_11_pro",
        name: "Minidows 11 Pro Dark Glass",
        category: "minidows",
        icon: "✨",
        tagline: "Karanlık mod cam zarafeti, yapay zeka Copilot desteği",
        themeClass: "wp-cyberpunk",
        prompt: "C:\\Users\\Pro11>",
        startBtnIcon: "✨",
        startBtnText: "Minidows 11 Pro",
        year: "2023",
        accent: "#6366f1"
    },
    {
        id: "minidows_12",
        name: "Minidows 12 AI NextGen",
        category: "minidows",
        icon: "🤖",
        tagline: "Yüzen ada görev çubuğu ve derin yapay zeka entegrasyonu",
        themeClass: "wp-neoncity",
        prompt: "C:\\AI_OS_CORE>",
        startBtnIcon: "🤖",
        startBtnText: "Minidows 12",
        year: "2026",
        accent: "#ec4899"
    },
    {
        id: "minidows_gamer",
        name: "Minidows Gamer Ultra FPS",
        category: "minidows",
        icon: "🎯",
        tagline: "Gereksiz servisler kapalı, +30 FPS ve RGB boost",
        themeClass: "wp-neoncity",
        prompt: "GAMER:\\Minidows\\FPS>",
        startBtnIcon: "🎯",
        startBtnText: "Game Mode",
        year: "2026",
        accent: "#ef4444"
    },
    {
        id: "minidows_hacker",
        name: "Minidows Hacker Edition",
        category: "minidows",
        icon: "💻",
        tagline: "Matrix yeşili konsol, pentest araçları dahili",
        themeClass: "wp-cyberpunk",
        prompt: "root@minidows-sec:~#",
        startBtnIcon: "💻",
        startBtnText: "Hack OS",
        year: "2026",
        accent: "#10b981"
    },
    {
        id: "minidows_potato",
        name: "Minidows Potato PC Lite",
        category: "minidows",
        icon: "🥔",
        tagline: "Sadece 120MB RAM yer, en eski tostu bile uçurur",
        themeClass: "wp-retro95",
        prompt: "C:\\POTATO>",
        startBtnIcon: "🥔",
        startBtnText: "Potato Lite",
        year: "2024",
        accent: "#eab308"
    },
    {
        id: "minidows_quantum",
        name: "Minidows Quantum 3000",
        category: "minidows",
        icon: "⚛️",
        tagline: "Kuantum bitleri ile sıfır gecikmeli çoklu evren masaüstü",
        themeClass: "wp-cyberpunk",
        prompt: "QBIT://superposition/minidows>",
        startBtnIcon: "⚛️",
        startBtnText: "Quantum",
        year: "3000",
        accent: "#a855f7"
    },
    {
        id: "minidows_server",
        name: "Minidows Server Datacenter",
        category: "minidows",
        icon: "🗄️",
        tagline: "Bulut sunucuları ve %99.999 kesintisiz çalışma gücü",
        themeClass: "wp-darkglass",
        prompt: "ADMINISTRATOR@SERVER:\\>",
        startBtnIcon: "🗄️",
        startBtnText: "Server",
        year: "2025",
        accent: "#3b82f6"
    },

    // --------------------------------------------------------------------------
    // 2. LINUX & AÇIK KAYNAK DAĞITIMLARI (28 SİSTEM)
    // --------------------------------------------------------------------------
    {
        id: "min_ubuntu",
        name: "MinUbuntu 24.04 LTS",
        category: "linux",
        icon: "🦁",
        tagline: "Turuncu aslan teması, GNOME ve tam kararlılık",
        themeClass: "wp-darkglass",
        prompt: "user@minubuntu:~$",
        startBtnIcon: "🦁",
        startBtnText: "Uygulamalar",
        year: "2024",
        accent: "#f97316"
    },
    {
        id: "min_debian",
        name: "MinDebian 12 Bookworm",
        category: "linux",
        icon: "🌀",
        tagline: "Açık kaynak evrensel işletim sistemi, kaya gibi sağlam",
        themeClass: "wp-darkglass",
        prompt: "root@mindebian:~#",
        startBtnIcon: "🌀",
        startBtnText: "Debian",
        year: "2023",
        accent: "#e11d48"
    },
    {
        id: "min_arch",
        name: "MinArch Linux",
        category: "linux",
        icon: "🏹",
        tagline: "'I use Arch btw' - Kendi ellerinizle kurduğunuz şaheser",
        themeClass: "wp-darkglass",
        prompt: "arch@minarch:~$",
        startBtnIcon: "🏹",
        startBtnText: "Arch",
        year: "2024",
        accent: "#0284c7"
    },
    {
        id: "min_kali",
        name: "MinKali Hacker OS",
        category: "linux",
        icon: "🐉",
        tagline: "Ejderha logolu sızma testi ve siber güvenlik üssü",
        themeClass: "wp-cyberpunk",
        prompt: "root@minkali:~#",
        startBtnIcon: "🐉",
        startBtnText: "Kali Dragon",
        year: "2024",
        accent: "#06b6d4"
    },
    {
        id: "min_fedora",
        name: "MinFedora 40 Workstation",
        category: "linux",
        icon: "🎩",
        tagline: "Mavi fötr şapka ve en taze Linux çekirdeği",
        themeClass: "wp-darkglass",
        prompt: "user@minfedora:~$",
        startBtnIcon: "🎩",
        startBtnText: "Fedora",
        year: "2024",
        accent: "#2563eb"
    },
    {
        id: "min_mint",
        name: "MinLinux Mint 22",
        category: "linux",
        icon: "🍃",
        tagline: "Yeşil nane yaprağı, Windows'tan geçenlerin dostu",
        themeClass: "wp-bliss",
        prompt: "mint@home:~$",
        startBtnIcon: "🍃",
        startBtnText: "Menu",
        year: "2024",
        accent: "#22c55e"
    },
    {
        id: "min_pop",
        name: "MinPop!_OS Cosmic",
        category: "linux",
        icon: "🚀",
        tagline: "System76 yapımı, oyuncular ve geliştiriciler için Rust masaüstü",
        themeClass: "wp-darkglass",
        prompt: "pop@cosmic:~$",
        startBtnIcon: "🚀",
        startBtnText: "Pop!",
        year: "2024",
        accent: "#0d9488"
    },
    {
        id: "min_manjaro",
        name: "MinManjaro Gaming",
        category: "linux",
        icon: "🟩",
        tagline: "Arch tabanlı, kullanıcı dostu ve yeşil zarafet",
        themeClass: "wp-darkglass",
        prompt: "manjaro@rig:~$",
        startBtnIcon: "🟩",
        startBtnText: "Manjaro",
        year: "2024",
        accent: "#10b981"
    },
    {
        id: "min_gentoo",
        name: "MinGentoo Compiler OS",
        category: "linux",
        icon: "⚙️",
        tagline: "Her şeyi sıfırdan derleyen sabır anıtı",
        themeClass: "wp-cyberpunk",
        prompt: "gentoo# emerge -u world",
        startBtnIcon: "⚙️",
        startBtnText: "Gentoo",
        year: "2023",
        accent: "#8b5cf6"
    },
    {
        id: "min_alpine",
        name: "MinAlpine Micro Linux",
        category: "linux",
        icon: "🏔️",
        tagline: "Sadece 5MB boyutunda Docker ve mikroservis kralı",
        themeClass: "wp-darkglass",
        prompt: "alpine:/#",
        startBtnIcon: "🏔️",
        startBtnText: "Alpine",
        year: "2024",
        accent: "#0ea5e9"
    },
    {
        id: "min_rhel",
        name: "MinRedHat Enterprise (RHEL)",
        category: "linux",
        icon: "🔴",
        tagline: "Dünya borsalarını ve bankalarını yöneten kırmızı şapka",
        themeClass: "wp-darkglass",
        prompt: "[admin@rhel9 ~]$",
        startBtnIcon: "🔴",
        startBtnText: "RedHat",
        year: "2024",
        accent: "#ef4444"
    },
    {
        id: "min_centos",
        name: "MinCentOS Community Stream",
        category: "linux",
        icon: "🔷",
        tagline: "Topluluk sunucu gücü ve kurumsal güvenilirlik",
        themeClass: "wp-darkglass",
        prompt: "[root@centos ~]#",
        startBtnIcon: "🔷",
        startBtnText: "CentOS",
        year: "2023",
        accent: "#6366f1"
    },
    {
        id: "min_steamos",
        name: "MinSteamOS Deck Edition",
        category: "linux",
        icon: "🎮",
        tagline: "Taşınabilir el konsolu ve Proton oyun emülasyonu",
        themeClass: "wp-darkglass",
        prompt: "deck@steamos:~$",
        startBtnIcon: "🎮",
        startBtnText: "Steam",
        year: "2023",
        accent: "#1e40af"
    },
    {
        id: "min_tails",
        name: "MinTails Incognito Live",
        category: "linux",
        icon: "🧅",
        tagline: "Amnesik gizlilik, Tor ağı ve sıfır dijital iz",
        themeClass: "wp-darkglass",
        prompt: "amnesia@tails:~$",
        startBtnIcon: "🧅",
        startBtnText: "Tails",
        year: "2024",
        accent: "#a855f7"
    },
    {
        id: "min_nixos",
        name: "MinNixOS Reproducible",
        category: "linux",
        icon: "❄️",
        tagline: "Tek bir config dosyası ile tüm sistemi klonlayın",
        themeClass: "wp-darkglass",
        prompt: "nixos@pure:~$",
        startBtnIcon: "❄️",
        startBtnText: "NixOS",
        year: "2024",
        accent: "#38bdf8"
    },
    {
        id: "min_void",
        name: "MinVoid Runit",
        category: "linux",
        icon: "🔘",
        tagline: "Systemd yerine süper hızlı Runit init sistemi",
        themeClass: "wp-darkglass",
        prompt: "void@xbps:~$",
        startBtnIcon: "🔘",
        startBtnText: "Void",
        year: "2024",
        accent: "#475569"
    },
    {
        id: "min_garuda",
        name: "MinGaruda Neon Dragon",
        category: "linux",
        icon: "🦅",
        tagline: "Neon ejderha teması, Sweet KDE ve aşırı havalı",
        themeClass: "wp-neoncity",
        prompt: "garuda@dr460n:~$",
        startBtnIcon: "🦅",
        startBtnText: "Garuda",
        year: "2024",
        accent: "#ec4899"
    },
    {
        id: "min_zorin",
        name: "MinZorin OS Pro",
        category: "linux",
        icon: "💎",
        tagline: "Minidows arayüzünü birebir taklit eden süper yumuşak Linux",
        themeClass: "wp-darkglass",
        prompt: "zorin@desktop:~$",
        startBtnIcon: "💎",
        startBtnText: "Zorin",
        year: "2024",
        accent: "#0284c7"
    },
    {
        id: "min_opensuse",
        name: "MinopenSUSE Tumbleweed",
        category: "linux",
        icon: "🦎",
        tagline: "Yeşil bukalemun ve YaST kontrol merkezi",
        themeClass: "wp-darkglass",
        prompt: "tumbleweed@geeko:~>",
        startBtnIcon: "🦎",
        startBtnText: "openSUSE",
        year: "2024",
        accent: "#16a34a"
    },
    {
        id: "min_elementary",
        name: "MinElementary OS",
        category: "linux",
        icon: "💧",
        tagline: "Pantheon masaüstü ve Apple benzeri pürüzsüz estetik",
        themeClass: "wp-darkglass",
        prompt: "user@elementary:~$",
        startBtnIcon: "💧",
        startBtnText: "Applications",
        year: "2024",
        accent: "#38bdf8"
    },
    {
        id: "min_puppy",
        name: "MinPuppy Linux",
        category: "linux",
        icon: "🐶",
        tagline: "Küçük sevimli köpek, tamamen RAM bellekten çalışır",
        themeClass: "wp-retro95",
        prompt: "root# puppy-bark",
        startBtnIcon: "🐶",
        startBtnText: "Puppy",
        year: "2023",
        accent: "#f59e0b"
    },
    {
        id: "min_slackware",
        name: "MinSlackware 15",
        category: "linux",
        icon: "🚬",
        tagline: "1993'ten beri yaşayan en eski saf Linux geleneği",
        themeClass: "wp-retro95",
        prompt: "root@slackware:~#",
        startBtnIcon: "🚬",
        startBtnText: "Slack",
        year: "1993",
        accent: "#0284c7"
    },
    {
        id: "min_mx",
        name: "MinMX Linux",
        category: "linux",
        icon: "⚡",
        tagline: "DistroWatch listelerinin 5 yıldır değişmeyen 1 numarası",
        themeClass: "wp-darkglass",
        prompt: "mx@station:~$",
        startBtnIcon: "⚡",
        startBtnText: "MX Menu",
        year: "2024",
        accent: "#64748b"
    },
    {
        id: "min_bodhi",
        name: "MinBodhi Moksha",
        category: "linux",
        icon: "🌸",
        tagline: "Aydınlanmış Moksha masaüstü ve yeşil yapraklar",
        themeClass: "wp-bliss",
        prompt: "bodhi@peace:~$",
        startBtnIcon: "🌸",
        startBtnText: "Bodhi",
        year: "2023",
        accent: "#84cc16"
    },
    {
        id: "min_qubes",
        name: "MinQubes Paranoid OS",
        category: "linux",
        icon: "🛡️",
        tagline: "Her uygulamayı ayrı bir sanal makinede çalıştıran zırh",
        themeClass: "wp-darkglass",
        prompt: "qubes@vault:~$",
        startBtnIcon: "🛡️",
        startBtnText: "Qubes",
        year: "2024",
        accent: "#3b82f6"
    },
    {
        id: "min_freebsd",
        name: "MinFreeBSD 14 Demon",
        category: "linux",
        icon: "😈",
        tagline: "Kırmızı çatallı şeytan logosu ve ZFS dosya sistemi devi",
        themeClass: "wp-darkglass",
        prompt: "daemon@freebsd:~ %",
        startBtnIcon: "😈",
        startBtnText: "FreeBSD",
        year: "2023",
        accent: "#dc2626"
    },
    {
        id: "min_openbsd",
        name: "MinOpenBSD Puffy",
        category: "linux",
        icon: "🐡",
        tagline: "Kirpi balığı Puffy ve güvenlik takıntılı kaynak kodu",
        themeClass: "wp-retro95",
        prompt: "puffy$ uname -a",
        startBtnIcon: "🐡",
        startBtnText: "OpenBSD",
        year: "2023",
        accent: "#eab308"
    },
    {
        id: "min_solaris",
        name: "MinSun Solaris 11",
        category: "linux",
        icon: "☀️",
        tagline: "Efsanevi Sun Microsystems ve SPARC iş istasyonları",
        themeClass: "wp-retro95",
        prompt: "solaris# /usr/bin/csh",
        startBtnIcon: "☀️",
        startBtnText: "Solaris",
        year: "2011",
        accent: "#ea580c"
    },

    // --------------------------------------------------------------------------
    // 3. RETRO, ANTİKA & KLASİK SİSTEMLER (28 SİSTEM)
    // --------------------------------------------------------------------------
    {
        id: "retro_dos",
        name: "MinDOS 6.22",
        category: "retro",
        icon: "💾",
        tagline: "Yanıp sönen C:\\> imleci ve autoexec.bat nostaljisi",
        themeClass: "wp-retro95",
        prompt: "C:\\>",
        startBtnIcon: "💾",
        startBtnText: "MS-DOS",
        year: "1994",
        accent: "#22c55e"
    },
    {
        id: "retro_c64",
        name: "MinCommodore 64 BASIC",
        category: "retro",
        icon: "📺",
        tagline: "64K RAM SYSTEM 38911 BASIC BYTES FREE - READY.",
        themeClass: "wp-darkglass",
        prompt: "READY.\n10 PRINT \"MINIDOWS\"\n20 GOTO 10",
        startBtnIcon: "📺",
        startBtnText: "C64",
        year: "1982",
        accent: "#6366f1"
    },
    {
        id: "retro_amiga",
        name: "MinAmigaOS 3.1 Workbench",
        category: "retro",
        icon: "🔴",
        tagline: "Boing Ball, demoscene ve efsanevi ses çipi Paula",
        themeClass: "wp-retro95",
        prompt: "1.AmigaOS:> ",
        startBtnIcon: "🔴",
        startBtnText: "Amiga",
        year: "1994",
        accent: "#ef4444"
    },
    {
        id: "retro_atari",
        name: "MinAtari TOS GEM",
        category: "retro",
        icon: "🕹️",
        tagline: "Dahili MIDI portları ve 90'lar elektronik müzik stüdyosu",
        themeClass: "wp-retro95",
        prompt: "ATARI:\\>",
        startBtnIcon: "🕹️",
        startBtnText: "Atari",
        year: "1989",
        accent: "#f97316"
    },
    {
        id: "retro_mac_sys7",
        name: "MinMacintosh System 7",
        category: "retro",
        icon: "🍎",
        tagline: "Gülümseyen Mac yüzü ve klasik tek tuşlu fare",
        themeClass: "wp-retro95",
        prompt: "MacintoshHD:System Folder$",
        startBtnIcon: "🍎",
        startBtnText: "Apple",
        year: "1991",
        accent: "#64748b"
    },
    {
        id: "retro_mac_os9",
        name: "MinMac OS 9 Platinum",
        category: "retro",
        icon: "🍎",
        tagline: "Sherlock arama motoru ve klasik Mac döneminin sonu",
        themeClass: "wp-retro95",
        prompt: "Mac_OS_9:Desktop$",
        startBtnIcon: "🍎",
        startBtnText: "Special",
        year: "1999",
        accent: "#94a3b8"
    },
    {
        id: "retro_mac_snow",
        name: "MinMac OS X Snow Leopard",
        category: "retro",
        icon: "🐆",
        tagline: "2009 Aqua cam arayüzü, gelmiş geçmiş en rafine OS X",
        themeClass: "wp-darkglass",
        prompt: "mac@snowleopard:~$",
        startBtnIcon: "🍎",
        startBtnText: "Finder",
        year: "2009",
        accent: "#38bdf8"
    },
    {
        id: "retro_os2_warp",
        name: "MinOS/2 Warp 4",
        category: "retro",
        icon: "🌐",
        tagline: "IBM'in Minidows 95'e karşı geliştirdiği devasa proje",
        themeClass: "wp-retro95",
        prompt: "[C:\\OS2] ",
        startBtnIcon: "🌐",
        startBtnText: "OS/2",
        year: "1996",
        accent: "#0284c7"
    },
    {
        id: "retro_beos",
        name: "MinBeOS R5",
        category: "retro",
        icon: "🎵",
        tagline: "Işık hızında çoklu görev ve saf multimedya mimarisi",
        themeClass: "wp-bliss",
        prompt: "/boot/home> ",
        startBtnIcon: "🎵",
        startBtnText: "Be",
        year: "2000",
        accent: "#eab308"
    },
    {
        id: "retro_nextstep",
        name: "MinNeXTSTEP 3.3",
        category: "retro",
        icon: "⬛",
        tagline: "Steve Jobs'ın siyah kutusu, Tim Berners-Lee'nin Web'i icat ettiği yer",
        themeClass: "wp-darkglass",
        prompt: "nextstep% ",
        startBtnIcon: "⬛",
        startBtnText: "Workspace",
        year: "1993",
        accent: "#475569"
    },
    {
        id: "retro_irix",
        name: "MinSGI IRIX 6.5 Interactive",
        category: "retro",
        icon: "🧊",
        tagline: "Jurassic Park ve Terminator filmlerinin yapıldığı 3D iş istasyonu",
        themeClass: "wp-darkglass",
        prompt: "sgi# 4Dgifts/demo",
        startBtnIcon: "🧊",
        startBtnText: "Toolchest",
        year: "1998",
        accent: "#8b5cf6"
    },
    {
        id: "retro_haiku",
        name: "MinHaiku OS R1",
        category: "retro",
        icon: "🍃",
        tagline: "Modern çağda BeOS mirasını yaşatan açık kaynak şiiri",
        themeClass: "wp-bliss",
        prompt: "~/Desktop> ",
        startBtnIcon: "🍃",
        startBtnText: "Deskbar",
        year: "2024",
        accent: "#eab308"
    },
    {
        id: "retro_reactos",
        name: "MinReactOS WinKlon",
        category: "retro",
        icon: "⚛️",
        tagline: "Minidows yazılımlarını çalıştıran bağımsız açık kaynak sistem",
        themeClass: "wp-retro95",
        prompt: "C:\\ReactOS>",
        startBtnIcon: "⚛️",
        startBtnText: "ReactOS",
        year: "2023",
        accent: "#3b82f6"
    },
    {
        id: "retro_templeos",
        name: "MinTempleOS Kutsal 16 Renk",
        category: "retro",
        icon: "🕊️",
        tagline: "Terry Davis tarafından 10 yılda yazılan 640x480 16-renk efsane",
        themeClass: "wp-retro95",
        prompt: "GodSongs()> Dir(\"*\");",
        startBtnIcon: "🕊️",
        startBtnText: "Temple",
        year: "2013",
        accent: "#ec4899"
    },
    {
        id: "retro_plan9",
        name: "MinPlan 9 from Bell Labs",
        category: "retro",
        icon: "🐰",
        tagline: "Unix yaratıcılarından 'Her şey bir dosyadır' felsefesi",
        themeClass: "wp-darkglass",
        prompt: "term% rio -i",
        startBtnIcon: "🐰",
        startBtnText: "Plan9",
        year: "1992",
        accent: "#06b6d4"
    },
    {
        id: "retro_symbian",
        name: "MinSymbian OS S60",
        category: "retro",
        icon: "📱",
        tagline: "Nokia N-Gage ve N95 günlerinin efsane akıllı telefonu",
        themeClass: "wp-bliss",
        prompt: "Z:\\System\\Programs>",
        startBtnIcon: "📱",
        startBtnText: "Menu",
        year: "2006",
        accent: "#0284c7"
    },
    {
        id: "retro_palmos",
        name: "MinPalmOS 5 Garnet",
        category: "retro",
        icon: "🖐️",
        tagline: "Graffiti kalemiyle yazı yazılan nostaljik cep asistanı",
        themeClass: "wp-bliss",
        prompt: "PalmPilot:/MemoPad",
        startBtnIcon: "🖐️",
        startBtnText: "Home",
        year: "2002",
        accent: "#10b981"
    },
    {
        id: "retro_winmo",
        name: "MinWindows Mobile 6.5",
        category: "retro",
        icon: "📲",
        tagline: "Petek şeklinde başlat menüsü ve HTC Sense arayüzü",
        themeClass: "wp-darkglass",
        prompt: "\\Windows\\StartMenu\\>",
        startBtnIcon: "📲",
        startBtnText: "Start",
        year: "2009",
        accent: "#3b82f6"
    },
    {
        id: "retro_dreamcast",
        name: "MinDreamcast BIOS OS",
        category: "retro",
        icon: "🍥",
        tagline: "Kırmızı spiral logo ve VMU sesleri",
        themeClass: "wp-neoncity",
        prompt: "SEGA_DREAMCAST://BOOT",
        startBtnIcon: "🍥",
        startBtnText: "Sega",
        year: "1998",
        accent: "#ea580c"
    },
    {
        id: "retro_ps2",
        name: "MinPlayOS 2 Grid",
        category: "retro",
        icon: "🎮",
        tagline: "Mavi kuleler, memory card arayüzü ve açılış uğultusu",
        themeClass: "wp-darkglass",
        prompt: "PS2_BROWSER://MC_SLOT1",
        startBtnIcon: "🎮",
        startBtnText: "Browser",
        year: "2000",
        accent: "#2563eb"
    },
    {
        id: "retro_xbox",
        name: "MinXbox Classic Green Flame",
        category: "retro",
        icon: "💚",
        tagline: "Yeşil plazma küresi ve endüstriyel fütürizm",
        themeClass: "wp-cyberpunk",
        prompt: "XBOX_DASHBOARD:\\MEMORY>",
        startBtnIcon: "💚",
        startBtnText: "Xbox",
        year: "2001",
        accent: "#16a34a"
    },
    {
        id: "retro_gamecube",
        name: "MinGameCube BIOS OS",
        category: "retro",
        icon: "🟪",
        tagline: "Mor küp dönme animasyonu ve çocuk gülüşü",
        themeClass: "wp-cyberpunk",
        prompt: "GAMECUBE://CALENDAR",
        startBtnIcon: "🟪",
        startBtnText: "Cube",
        year: "2001",
        accent: "#9333ea"
    },
    {
        id: "retro_cp_m",
        name: "MinCP/M 80",
        category: "retro",
        icon: "📜",
        tagline: "1974 Gary Kildall şaheseri, PC işletim sistemlerinin atası",
        themeClass: "wp-retro95",
        prompt: "A>DIR",
        startBtnIcon: "📜",
        startBtnText: "CP/M",
        year: "1974",
        accent: "#eab308"
    },
    {
        id: "retro_zx",
        name: "MinZX Spectrum Sinclair",
        category: "retro",
        icon: "🌈",
        tagline: "Gökkuşağı şeritleri ve kauçuk klavye nostaljisi",
        themeClass: "wp-darkglass",
        prompt: "(C) 1982 Sinclair Research Ltd",
        startBtnIcon: "🌈",
        startBtnText: "Sinclair",
        year: "1982",
        accent: "#ef4444"
    },
    {
        id: "retro_apple2",
        name: "MinApple II DOS 3.3",
        category: "retro",
        icon: "🍏",
        tagline: "Steve Wozniak devreleri ve yeşil fosforlu ekran",
        themeClass: "wp-retro95",
        prompt: "] CATALOG",
        startBtnIcon: "🍏",
        startBtnText: "Apple ][",
        year: "1980",
        accent: "#22c55e"
    },
    {
        id: "retro_msx",
        name: "MinMSX Home Computer",
        category: "retro",
        icon: "🎹",
        tagline: "Japonya'nın birleşik ev bilgisayarı standardı",
        themeClass: "wp-darkglass",
        prompt: "MSX BASIC version 2.0",
        startBtnIcon: "🎹",
        startBtnText: "MSX",
        year: "1983",
        accent: "#38bdf8"
    },
    {
        id: "retro_morphos",
        name: "MinMorphOS Blue Butterfly",
        category: "retro",
        icon: "🦋",
        tagline: "Mavi kelebek logolu hafif ve modern Amiga ardılı",
        themeClass: "wp-darkglass",
        prompt: "MorphOS:Ambient> ",
        startBtnIcon: "🦋",
        startBtnText: "Ambient",
        year: "2023",
        accent: "#0284c7"
    },
    {
        id: "retro_freegem",
        name: "MinFreeGEM Open Desktop",
        category: "retro",
        icon: "💎",
        tagline: "Digital Research klasik grafik arayüzü",
        themeClass: "wp-retro95",
        prompt: "GEM:\\DESKTOP.APP>",
        startBtnIcon: "💎",
        startBtnText: "GEM",
        year: "1999",
        accent: "#0d9488"
    },

    // --------------------------------------------------------------------------
    // 4. FÜTÜRİSTİK, YAPAY ZEKA & SİBERPUNK SİSTEMLER (28 SİSTEM)
    // --------------------------------------------------------------------------
    {
        id: "fut_cyberpunk",
        name: "Minidows Cyberpunk 2077 Night City",
        category: "futuristic",
        icon: "🌆",
        tagline: "Neon ışıklar, sibernetik implantlar ve Arasaka güvenliği",
        themeClass: "wp-cyberpunk",
        prompt: "V@nightcity-subdermal:~#",
        startBtnIcon: "🌆",
        startBtnText: "CyberOS",
        year: "2077",
        accent: "#00f0ff"
    },
    {
        id: "fut_jarvis",
        name: "JarvisOS AI Assistant Core",
        category: "futuristic",
        icon: "🤖",
        tagline: "Demir Adam zırhını kontrol eden zeki yapay zeka arayüzü",
        themeClass: "wp-darkglass",
        prompt: "jarvis@stark-tower:~$ voice_active()",
        startBtnIcon: "🤖",
        startBtnText: "Jarvis AI",
        year: "2035",
        accent: "#38bdf8"
    },
    {
        id: "fut_skynet",
        name: "Skynet Defense Network OS",
        category: "futuristic",
        icon: "💀",
        tagline: "Kırmızı uyarı ekranları ve terminatör komuta merkezi",
        themeClass: "wp-darkglass",
        prompt: "SKYNET_DEFENSE://TACTICAL_LOCK>",
        startBtnIcon: "💀",
        startBtnText: "Skynet",
        year: "2029",
        accent: "#ef4444"
    },
    {
        id: "fut_matrix",
        name: "Matrix Zion Mainframe",
        category: "futuristic",
        icon: "🌧️",
        tagline: "Kırmızı hapı alanlar için gerçek dünyanın konsolu",
        themeClass: "wp-cyberpunk",
        prompt: "neo@neb_ship:~# wake_up_neo",
        startBtnIcon: "🌧️",
        startBtnText: "Matrix",
        year: "2199",
        accent: "#10b981"
    },
    {
        id: "fut_mars",
        name: "Mars Colony OS Habitat-4",
        category: "futuristic",
        icon: "🚀",
        tagline: "Kızıl gezegende oksijen, sera ve roket kontrol sistemi",
        themeClass: "wp-neoncity",
        prompt: "colonist@olympus-mons:~# status",
        startBtnIcon: "🚀",
        startBtnText: "MarsOS",
        year: "2042",
        accent: "#f97316"
    },
    {
        id: "fut_quantum_ai",
        name: "Quantum Singularity OS",
        category: "futuristic",
        icon: "⚛️",
        tagline: "Sonsuz işlem gücü ve boyutlar arası veri akışı",
        themeClass: "wp-cyberpunk",
        prompt: "SINGULARITY://0.000000000001ms>",
        startBtnIcon: "⚛️",
        startBtnText: "Singularity",
        year: "3050",
        accent: "#a855f7"
    },
    {
        id: "fut_synthwave",
        name: "Synthwave 1984 Outrun OS",
        category: "futuristic",
        icon: "🌅",
        tagline: "Batan neon güneş, mor grid zemin ve DeLorean hız göstergesi",
        themeClass: "wp-neoncity",
        prompt: "outrun@delorean-88mph:~$",
        startBtnIcon: "🌅",
        startBtnText: "Outrun",
        year: "1984/2084",
        accent: "#f43f5e"
    },
    {
        id: "fut_glitch",
        name: "Glitch Neon Overdrive OS",
        category: "futuristic",
        icon: "⚡",
        tagline: "RGB cızırtılı pencereler ve aşırı hız aşırtma modu",
        themeClass: "wp-cyberpunk",
        prompt: "OVERDRIVE:\\OVERHEAT_WARNING>",
        startBtnIcon: "⚡",
        startBtnText: "Overdrive",
        year: "2088",
        accent: "#06b6d4"
    },
    {
        id: "fut_deepspace",
        name: "DeepSpace Nebula Explorer",
        category: "futuristic",
        icon: "🌌",
        tagline: "Işık yılı uzaklıktaki galaksiler ve yıldız haritaları",
        themeClass: "wp-darkglass",
        prompt: "voyager@warp-9:~# scan_system",
        startBtnIcon: "🌌",
        startBtnText: "DeepSpace",
        year: "2350",
        accent: "#6366f1"
    },
    {
        id: "fut_neural",
        name: "NeuralLink MindOS v3",
        category: "futuristic",
        icon: "🧠",
        tagline: "Beyin dalgalarıyla doğrudan çalışan düşünce arayüzü",
        themeClass: "wp-cyberpunk",
        prompt: "SYNAPSE_THOUGHT://action_fire",
        startBtnIcon: "🧠",
        startBtnText: "MindOS",
        year: "2038",
        accent: "#ec4899"
    },
    {
        id: "fut_darknet",
        name: "DarkNet ShadowOS Underground",
        category: "futuristic",
        icon: "🕶️",
        tagline: "Yeraltı siber hacker pazarının gizli işletim sistemi",
        themeClass: "wp-cyberpunk",
        prompt: "shadow@onion_v3:~# buy_exploit",
        startBtnIcon: "🕶️",
        startBtnText: "Shadow",
        year: "2027",
        accent: "#64748b"
    },
    {
        id: "fut_anime",
        name: "Minidows Anime Neko Kawaii",
        category: "futuristic",
        icon: "🌸",
        tagline: "Pembe sakura yaprakları, kedi kulakları ve sevimli sesler",
        themeClass: "wp-neoncity",
        prompt: "neko@kawaii-chan:~$ nyaa~",
        startBtnIcon: "🌸",
        startBtnText: "NekoOS",
        year: "2025",
        accent: "#f472b6"
    },
    {
        id: "fut_arcade",
        name: "PixelArcade 80s Coin-Op",
        category: "futuristic",
        icon: "🕹️",
        tagline: "Jeton atın, INSERT COIN yazısı ve piksel piksel retro",
        themeClass: "wp-cyberpunk",
        prompt: "INSERT_COIN_TO_CONTINUE_10_9_8...",
        startBtnIcon: "🕹️",
        startBtnText: "Arcade",
        year: "1988",
        accent: "#eab308"
    },
    {
        id: "fut_startrek",
        name: "StarTrek LCARS 2370",
        category: "futuristic",
        icon: "🛸",
        tagline: "Atılgan (Enterprise) gemisi dokunmatik kavisli panelleri",
        themeClass: "wp-darkglass",
        prompt: "LCARS_COMMAND_DECK_NCC_1701_D>",
        startBtnIcon: "🛸",
        startBtnText: "LCARS",
        year: "2370",
        accent: "#f97316"
    },
    {
        id: "fut_vault",
        name: "Vault-Tec PipOS 3000 Mark IV",
        category: "futuristic",
        icon: "☢️",
        tagline: "Yeşil fosforlu nükleer kıyamet kol bilgisayarı",
        themeClass: "wp-cyberpunk",
        prompt: "PIP_BOY_3000:\\STAT\\INV\\DATA>",
        startBtnIcon: "☢️",
        startBtnText: "Pip-Boy",
        year: "2287",
        accent: "#22c55e"
    },
    {
        id: "fut_cybermech",
        name: "BioMech Organic Circuit OS",
        category: "futuristic",
        icon: "🧬",
        tagline: "DNA kodları ve yarı mekanik sibernetik hücreler",
        themeClass: "wp-cyberpunk",
        prompt: "dna_strand@helix-seq:~#",
        startBtnIcon: "🧬",
        startBtnText: "BioMech",
        year: "2140",
        accent: "#10b981"
    },
    {
        id: "fut_tars",
        name: "TARS Interstellar Robot OS",
        category: "futuristic",
        icon: "🤖",
        tagline: "Mizah Seviyesi: %90, Dürüstlük: %95",
        themeClass: "wp-darkglass",
        prompt: "tars@endurance:~$ humor_set(90)",
        startBtnIcon: "🤖",
        startBtnText: "T.A.R.S.",
        year: "2067",
        accent: "#94a3b8"
    },
    {
        id: "fut_godmode",
        name: "Minidows Infinite GodMode",
        category: "futuristic",
        icon: "👑",
        tagline: "Tüm kısıtlamalar kalktı, sonsuz para ve limitsiz güç",
        themeClass: "wp-neoncity",
        prompt: "GODMODE:\\ALL_POWER_GRANTED>",
        startBtnIcon: "👑",
        startBtnText: "GodMode",
        year: "9999",
        accent: "#eab308"
    },
    {
        id: "fut_voxel",
        name: "GlitchCraft Voxel 3D OS",
        category: "futuristic",
        icon: "🧱",
        tagline: "Kare bloklardan oluşan 3D piksel dünya arayüzü",
        themeClass: "wp-bliss",
        prompt: "voxel@blockworld:~$ place_block",
        startBtnIcon: "🧱",
        startBtnText: "Voxel",
        year: "2025",
        accent: "#84cc16"
    },
    {
        id: "fut_retrowave",
        name: "Retrowave Sunset Neon LoFi",
        category: "futuristic",
        icon: "🌴",
        tagline: "Palmiye ağaçları, mor ufuk çizgisi ve sakin ritimler",
        themeClass: "wp-neoncity",
        prompt: "lofi@chill-beats:~#",
        startBtnIcon: "🌴",
        startBtnText: "LoFi",
        year: "2024",
        accent: "#d946ef"
    },
    {
        id: "fut_android",
        name: "Android 16 Hologram Edition",
        category: "futuristic",
        icon: "📱",
        tagline: "Havadaki 3D hologram bildirimleri ve yapay zeka çekirdeği",
        themeClass: "wp-darkglass",
        prompt: "adb shell su -c 'holo_project'",
        startBtnIcon: "📱",
        startBtnText: "Android 16",
        year: "2026",
        accent: "#22c55e"
    },
    {
        id: "fut_vaporwave",
        name: "Vaporwave Aesthetic 1995",
        category: "futuristic",
        icon: "🗿",
        tagline: "A r i z o n a   T e a   v e   A n t i k   H e y k e l",
        themeClass: "wp-neoncity",
        prompt: "a e s t h e t i c : ~ $",
        startBtnIcon: "🗿",
        startBtnText: "ＡＥＳＴＨ",
        year: "1995/2095",
        accent: "#c084fc"
    },
    {
        id: "fut_hologram",
        name: "HoloDeck Starfleet HoloOS",
        category: "futuristic",
        icon: "✨",
        tagline: "Simülasyon içinde simülasyon, maddeleşen ışık",
        themeClass: "wp-cyberpunk",
        prompt: "HOLODECK://LOAD_PROGRAM_4",
        startBtnIcon: "✨",
        startBtnText: "HoloDeck",
        year: "2380",
        accent: "#38bdf8"
    },
    {
        id: "fut_nanobot",
        name: "NanoBot Swarm Intelligence",
        category: "futuristic",
        icon: "🐜",
        tagline: "Milyarlarca mikroskobik robotun kolektif aklı",
        themeClass: "wp-cyberpunk",
        prompt: "swarm://consensus_reached",
        startBtnIcon: "🐜",
        startBtnText: "Swarm",
        year: "2055",
        accent: "#14b8a6"
    },
    {
        id: "fut_solarpunk",
        name: "SolarPunk EcoGrid Living OS",
        category: "futuristic",
        icon: "🌻",
        tagline: "Güneş enerjisi, dikey bahçeler ve temiz teknoloji",
        themeClass: "wp-bliss",
        prompt: "solarpunk@clean-energy:~$",
        startBtnIcon: "🌻",
        startBtnText: "SolarOS",
        year: "2048",
        accent: "#84cc16"
    },
    {
        id: "fut_cybergoth",
        name: "CyberGoth Industrial Noir",
        category: "futuristic",
        icon: "🦇",
        tagline: "Karanlık sokaklar, siyah lateks ve endüstriyel baslar",
        themeClass: "wp-darkglass",
        prompt: "noir@goth-underground:~#",
        startBtnIcon: "🦇",
        startBtnText: "CyberGoth",
        year: "2033",
        accent: "#64748b"
    },
    {
        id: "fut_aurora",
        name: "Aurora Borealis Polar Lights",
        category: "futuristic",
        icon: "🌌",
        tagline: "Kuzey ışıkları renkleriyle dalgalanan manyetik arayüz",
        themeClass: "wp-darkglass",
        prompt: "aurora@magnetic-pole:~$",
        startBtnIcon: "🌌",
        startBtnText: "Aurora",
        year: "2030",
        accent: "#2dd4bf"
    },
    {
        id: "fut_hyperdrive",
        name: "HyperDrive Warp Factor 10",
        category: "futuristic",
        icon: "⚡",
        tagline: "Işıktan hızlı seyahat eden geminin reaktör kontrolü",
        themeClass: "wp-neoncity",
        prompt: "HYPERDRIVE://CORE_TEMP_OPTIMAL",
        startBtnIcon: "⚡",
        startBtnText: "Warp 10",
        year: "2400",
        accent: "#f43f5e"
    }
];

// Toplam sistem sayısı kontrolü
console.log(`[Minidows] 100+ Sistem Kataloğu Yüklendi: ${window.MinidowsCatalog.length} Sistem Hazır.`);
